import "dotenv/config";
import { createClient } from "next-sanity";

const projectId = process.env.NEXT_PUBLIC_SANITY_PROJECT_ID;
const dataset = process.env.NEXT_PUBLIC_SANITY_DATASET;
const token = process.env.SANITY_API_TOKEN;

if (!projectId || !dataset || !token) {
  console.error(
    "Missing required environment variables: NEXT_PUBLIC_SANITY_PROJECT_ID, NEXT_PUBLIC_SANITY_DATASET, or SANITY_API_TOKEN",
  );
  process.exit(1);
}

const client = createClient({
  projectId,
  dataset,
  apiVersion: "2024-01-01",
  token,
  useCdn: false,
});

const apartments: any[] = [
  {
    _type: "apartment",
    _id: "oceanfront-honeymoon-suite",
    name: "Oceanfront Honeymoon Suite with Private Jacuzzi",
    slug: { _type: "slug", current: "oceanfront-honeymoon-suite" },
    description:
      "Fall in love with the sound of the waves. This intimate suite features a private terrace with a jacuzzi overlooking the ocean, a king-sized bed, and a luxurious bathroom.",
    apartmentType: "suite",
    capacity: 2,
    standardOccupancy: 2,
    bedrooms: 1,
    bathrooms: 1,
    bedConfiguration: [{ room: "master", bedType: "king", quantity: 1 }],
    size: 55,
    location: "beachfront",
    floor: 3,
    viewType: ["sea-view", "ocean-view"],
    buildingName: "Sunrise Pointe",
    unitNumber: "305",
    basePrice: 450,
    weekendPrice: 550,
    currency: "USD",
    cleaningFee: 60,
    serviceFee: 45,
    securityDeposit: 200,
    taxRate: 12,
    minimumStay: 2,
    maximumStay: 14,
    cancellationPolicy: "strict",
    features: [
      "wifi",
      "air-conditioning",
      "smart-tv",
      "balcony",
      "coffee-maker",
      "hair-dryer",
      "safe",
      "mini-bar",
      "sea-view",
      "private-parking",
      "hot-tub",
    ],
    tags: ["luxury", "romantic", "honeymoon", "beachfront"],
    petsAllowed: false,
    smokingAllowed: false,
    breakfastIncluded: true,
    parkingAvailable: true,
    parkingType: "valet",
    featured: true,
    isAccessible: false,
    isActive: true,
  },
  {
    _type: "apartment",
    _id: "family-3-bedroom-pool-view",
    name: "Spacious 3-Bedroom Family Apartment with Pool View",
    slug: { _type: "slug", current: "family-3-bedroom-pool-view" },
    description:
      "Perfect for families, this large apartment offers a fully equipped kitchen, separate living and dining areas, and a balcony with stunning pool views.",
    apartmentType: "apartment",
    capacity: 7,
    standardOccupancy: 5,
    bedrooms: 3,
    bathrooms: 2,
    bedConfiguration: [
      { room: "master", bedType: "queen", quantity: 1 },
      { room: "bedroom-2", bedType: "double", quantity: 1 },
      { room: "bedroom-3", bedType: "twin", quantity: 2 },
      { room: "living-room", bedType: "sofa-bed", quantity: 1 },
    ],
    size: 95,
    location: "pool-view",
    floor: 2,
    viewType: ["pool-view", "garden-view"],
    buildingName: "Garden Oasis",
    unitNumber: "210",
    basePrice: 320,
    weekendPrice: 380,
    currency: "USD",
    cleaningFee: 90,
    serviceFee: 50,
    securityDeposit: 250,
    taxRate: 10,
    extraGuestFee: 35,
    childrenFree: true,
    freeChildrenAge: 12,
    minimumStay: 3,
    maximumStay: 30,
    advanceBookingDays: 2,
    cancellationPolicy: "moderate",
    features: [
      "wifi",
      "full-kitchen",
      "air-conditioning",
      "smart-tv",
      "balcony",
      "washing-machine",
      "dryer",
      "dishwasher",
      "microwave",
      "refrigerator",
      "freezer",
      "oven",
      "stove",
      "hair-dryer",
      "free-parking",
      "workspace",
    ],
    tags: ["family-friendly", "long-stay", "budget-friendly", "pool-view"],
    popularityScore: 92,
    petsAllowed: false,
    smokingAllowed: false,
    breakfastIncluded: false,
    parkingAvailable: true,
    parkingType: "free",
    airportTransferAvailable: true,
    airportTransferFee: 75,
    houseRules: [
      {
        rule: "Pool hours",
        _type: "object",
        description: "The main pool is open from 8 AM to 8 PM.",
      },
      {
        rule: "Children must be supervised",
        _type: "object",
        description:
          "Children under 13 must be supervised by an adult in common areas.",
      },
    ],
    featured: false,
    isAccessible: false,
    isActive: true,
  },
  {
    _type: "apartment",
    _id: "modern-city-center-loft",
    name: "Modern City Center Loft with Workspace",
    slug: { _type: "slug", current: "modern-city-center-loft" },
    description:
      "A stylish and compact studio in the heart of the city. High-speed Wi-Fi, a dedicated workspace, and modern appliances make it ideal for business or a city break.",
    apartmentType: "studio",
    capacity: 2,
    standardOccupancy: 2,
    bedrooms: 0,
    bathrooms: 1,
    bedConfiguration: [{ room: "studio", bedType: "queen", quantity: 1 }],
    size: 32,
    location: "hotel-building",
    floor: 5,
    viewType: ["city-view"],
    buildingName: "The Metropolitan",
    unitNumber: "5C",
    basePrice: 150,
    weekendPrice: 180,
    currency: "USD",
    cleaningFee: 30,
    serviceFee: 25,
    taxRate: 10,
    minimumStay: 1,
    advanceBookingDays: 0,
    checkInTime: "14:00",
    checkOutTime: "12:00",
    lateCheckOutAvailable: true,
    lateCheckOutFee: 40,
    cancellationPolicy: "flexible",
    features: [
      "wifi",
      "kitchenette",
      "air-conditioning",
      "heating",
      "smart-tv",
      "hair-dryer",
      "safe",
      "mini-fridge",
      "microwave",
      "coffee-maker",
      "iron",
      "dedicated-workspace",
      "elevator",
    ],
    isAccessible: false,
    tags: ["business-travel", "modern", "budget-friendly"],
    popularityScore: 85,
    petsAllowed: false,
    smokingAllowed: false,
    smokingAreas: "designated",
    breakfastIncluded: false,
    parkingAvailable: false,
    featured: false,
    isActive: true,
  },
  {
    _type: "apartment",
    _id: "pet-friendly-garden-bungalow",
    name: "Cozy Garden Bungalow with Private Patio (Pet Friendly)",
    slug: { _type: "slug", current: "pet-friendly-garden-bungalow" },
    description:
      "Enjoy a private, detached bungalow surrounded by tropical gardens. Your furry friend is welcome here, with a fully fenced patio for their safety.",
    apartmentType: "villa",
    capacity: 3,
    standardOccupancy: 2,
    bedrooms: 1,
    bathrooms: 1,
    bedConfiguration: [{ room: "master", bedType: "queen", quantity: 1 }],
    size: 45,
    location: "garden-area",
    floor: 0,
    viewType: ["garden-view"],
    buildingName: "The Cottages at Palm Grove",
    unitNumber: "B-4",
    basePrice: 220,
    currency: "USD",
    cleaningFee: 75,
    securityDeposit: 150,
    petsAllowed: true,
    petFee: 25,
    petDeposit: 50,
    taxRate: 10,
    petRestrictions:
      "Maximum 2 dogs. Dogs under 25kg only. Must be leashed in common areas.",
    minimumStay: 2,
    cancellationPolicy: "moderate",
    features: [
      "wifi",
      "kitchenette",
      "air-conditioning",
      "smart-tv",
      "patio",
      "mini-fridge",
      "microwave",
      "coffee-maker",
      "bbq-grill",
      "free-parking",
      "workspace",
    ],
    tags: ["pet-friendly", "romantic", "garden-view", "eco-friendly"],
    distanceToBeach: 800,
    smokingAllowed: true,
    smokingAreas: "balcony-only",
    breakfastIncluded: false,
    parkingAvailable: true,
    parkingType: "free",
    featured: false,
    isAccessible: false,
    isActive: true,
  },
  {
    _type: "apartment",
    _id: "accessible-suite-roll-in-shower",
    name: "Accessible Suite with Roll-in Shower & Step-Free Access",
    slug: { _type: "slug", current: "accessible-suite-roll-in-shower" },
    description:
      "Designed with accessibility in mind, this ground-floor suite features wide doorways, a roll-in shower with grab bars, and step-free access throughout.",
    apartmentType: "suite",
    capacity: 2,
    standardOccupancy: 2,
    bedrooms: 1,
    bathrooms: 1,
    bedConfiguration: [{ room: "master", bedType: "queen", quantity: 1 }],
    size: 50,
    location: "hotel-building",
    floor: 0,
    viewType: ["garden-view"],
    unitNumber: "G-01",
    basePrice: 200,
    currency: "USD",
    cleaningFee: 40,
    serviceFee: 35,
    taxRate: 10,
    minimumStay: 1,
    cancellationPolicy: "flexible",
    features: [
      "wifi",
      "air-conditioning",
      "smart-tv",
      "patio",
      "mini-fridge",
      "coffee-maker",
      "hair-dryer",
      "free-parking",
      "garden-view",
    ],
    isAccessible: true,
    accessibilityFeatures: [
      "wheelchair-accessible",
      "step-free-entry",
      "wide-doorways",
      "grab-bars",
      "roll-in-shower",
      "lowered-fixtures",
      "accessible-parking",
    ],
    tags: ["accessible", "modern", "garden-view"],
    popularityScore: 78,
    petsAllowed: false,
    smokingAllowed: false,
    parkingAvailable: true,
    parkingType: "free",
    featured: false,
    isActive: true,
  },
];

async function seed() {
  console.log("Starting Sanity seeding...");
  for (const apartment of apartments) {
    try {
      await client.createOrReplace(apartment);
      console.log(`Seeded/Updated: ${apartment.name}`);
    } catch (error) {
      console.error(`Error seeding ${apartment.name}:`, error);
    }
  }
  console.log("Seeding completed!");
}

seed();
